apiVersion: v1
kind: Service
metadata:
  labels:
    name: auth-service
  name: auth-service
  namespace: springcloud
spec:
  type: ClusterIP
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    name: auth-service