apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq
  namespace: springcloud
spec:
  type: NodePort
  ports:
  - port: 5671
    protocol: TCP
    targetPort: 5671
  - port: 15672
    protocol: TCP
    targetPort: 15672
    nodePort: 15672
  selector:
    name: rabbitmq