apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notification-service
  namespace: springcloud
  labels:
    name: notification-service
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: notification-service
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: notification-service
        image: goodraincloudframeworks/piggymetrics-notification-service
        imagePullPolicy: IfNotPresent
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8000
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            cpu: 1000m
            memory: 1000Mi