apiVersion: v1
kind: Service
metadata:
  labels:
    name: gateway
  name: gateway
  namespace: springcloud
spec:
  type: ClusterIP
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    name: gateway