apiVersion: v1
kind: Service
metadata:
  labels:
    name: piggymetrics-config
  name: piggymetrics-config
  namespace: springcloud
spec:
  type: ClusterIP
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    name: piggymetrics-config