apiVersion: v1
kind: Service
metadata:
  labels:
    name: monitoring
  name: monitoring
  namespace: springcloud
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  - port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    name: monitoring